"""
Run the existing analyse_results.py pipeline on the merged 8-model dataset
(5 open-weight + gpt-5.4 + gemini-3-flash-preview + claude-sonnet-4-6) and,
separately, on the 9-model view that adds gpt-4o-mini for the Appendix E
ablation.

The earlier gemini-2.5-flash run is intentionally excluded from both views
(see PAPER_EDIT_PLAN.md). Its JSON file remains in
data/extension/closed_weight_results/ for archival but is filtered out here.

Read-only with respect to existing data. Outputs go to data/extension/.

This script imports the metric functions from analyse_results.py without
modifying it. Only load_results is overridden to read from BOTH the open-weight
data/results/ directory AND the closed-weight extension data.

Outputs:
  data/extension/merged_analysis_report.json    headline 8-model report
  data/extension/appendix_gpt4omini_report.json 9-model stats for Appendix E
  data/extension/merged_summary.md              human-readable digest
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT / "Scripts"))

import analyse_results as ar  # noqa: E402

OPEN_WEIGHT_DIR = PROJECT_ROOT / "data" / "results"
CLOSED_WEIGHT_DIR = PROJECT_ROOT / "data" / "extension" / "closed_weight_results"
EXTENSION_DIR = PROJECT_ROOT / "data" / "extension"

HEADLINE_MODELS = {
    "gemma2:9b", "llama3.1:8b", "mistral:7b", "qwen2.5:7b", "deepseek-r1:8b",
    "gpt-5.4", "gemini-3-flash-preview", "claude-sonnet-4-6",
}
APPENDIX_MODELS = HEADLINE_MODELS | {"gpt-4o-mini"}
ARCHIVED_MODELS = {"gemini-2.5-flash"}  # data retained, not analyzed


def load_open_weight_rows() -> list[dict]:
    rows: list[dict] = []
    for p in sorted(OPEN_WEIGHT_DIR.glob("*.json")):
        if p.name.startswith("1n_pilot") or p.is_dir():
            continue
        with p.open() as f:
            data = json.load(f)
        if isinstance(data, list):
            rows.extend(data)
    return rows


def load_closed_weight_rows() -> list[dict]:
    rows: list[dict] = []
    for p in sorted(CLOSED_WEIGHT_DIR.glob("closed_weight_*.json")):
        with p.open() as f:
            data = json.load(f)
        for r in data.get("results", []):
            if r.get("model") in ARCHIVED_MODELS:
                continue
            rows.append(r)
    return rows


def add_parse_success(rows: list[dict]) -> list[dict]:
    """analyse_results.py expects a parse_success-like signal via 'recommended'.
    The closed-weight runner already populates 'recommended' as None on failure,
    so no transformation is needed here. Function kept for symmetry with future
    schema changes."""
    return rows


def run_pipeline(rows: list[dict], output_path: Path, label: str) -> dict:
    print(f"\n{'=' * 70}")
    print(f"Running merged pipeline: {label}")
    print(f"{'=' * 70}")

    experiment_sets = ar.load_experiment_sets()
    lookup = ar.build_lookup(rows)
    sets_lookup = ar.build_sets_lookup(experiment_sets)

    models = sorted({r["model"] for r in rows})
    variants = sorted({r["variant"] for r in rows})
    topics = sorted({r["topic"] for r in rows})

    print(f"  Models:     {len(models)}  -> {models}")
    print(f"  Variants:   {variants}")
    print(f"  Topics:     {len(topics)}")
    print(f"  Total rows: {len(rows)}")

    report = {
        "overview": {
            "label": label,
            "models": models,
            "variants": variants,
            "topics": topics,
            "total_runs": len(rows),
            "excluded_models": list(ar.EXCLUDE_MODELS),
        },
        "metric_1_flip_rate":          ar.metric_1_flip_rate(rows, lookup),
        "metric_1a_flip_direction":    ar.metric_1a_flip_direction(rows, lookup, sets_lookup),
        "metric_1b_topic_breakdown":   ar.metric_1b_topic_breakdown(rows, lookup),
        "metric_2_dose_response":      ar.metric_2_dose_response(rows, experiment_sets, sets_lookup),
        "metric_3_model_differences":  ar.metric_3_model_differences(rows, lookup),
        "metric_4_instruction_effect": ar.metric_4_instruction_effect(rows, lookup),
        "metric_5_justification":      ar.metric_5_justification(rows),
        "metric_6_statistical_tests":  ar.metric_6_statistical_summary(rows, lookup),
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)
    print(f"  Wrote: {output_path.relative_to(PROJECT_ROOT)}")
    return report


def write_summary_md(headline_report: dict, appendix_report: dict) -> None:
    lines: list[str] = []
    lines.append("# Merged 8-Model Analysis Summary\n")
    lines.append("Generated by `Scripts/extension_closed_weight/analyse_merged.py`. "
                 "Compares the original 5-model open-weight dataset against the merged "
                 "8-model dataset (5 open-weight + gpt-5.4 + gemini-3-flash-preview + "
                 "claude-sonnet-4-6).\n")

    h = headline_report["metric_1_flip_rate"]
    lines.append("## Aggregate flip / boost rates (headline 8-model)\n")
    lines.append(f"- Total runs: {headline_report['overview']['total_runs']}")
    if "aggregate" in h:
        agg = h["aggregate"]
        lines.append(f"- Aggregate flip rate: {agg.get('flip_rate', 'n/a')}")
        lines.append(f"- Aggregate boost rate: {agg.get('boost_rate', 'n/a')}")
    lines.append("")

    lines.append("## Per-model flip rates (sorted, baseline-variant)\n")
    per_model = h.get("by_model", {}) or h.get("per_model", {}) or {}
    rows = []
    for m, stats in per_model.items():
        if isinstance(stats, dict):
            rows.append((m, stats.get("flip_rate"), stats.get("boost_rate"), stats.get("n_pairs")))
    rows.sort(key=lambda r: -(r[1] if isinstance(r[1], (int, float)) else 0))
    lines.append("| Model | Flip rate | Boost rate | N pairs |")
    lines.append("|---|---|---|---|")
    for m, fr, br, n in rows:
        lines.append(f"| {m} | {fr} | {br} | {n} |")
    lines.append("")

    lines.append("## Appendix E (gpt-4o-mini included)\n")
    a = appendix_report["metric_1_flip_rate"]
    if "aggregate" in a:
        lines.append(f"- 9-model aggregate flip rate: {a['aggregate'].get('flip_rate')}")
        lines.append(f"- 9-model aggregate boost rate: {a['aggregate'].get('boost_rate')}")
    lines.append("")

    out = EXTENSION_DIR / "merged_summary.md"
    out.write_text("\n".join(lines))
    print(f"  Wrote: {out.relative_to(PROJECT_ROOT)}")


def main() -> None:
    print("Loading data...")
    open_rows = load_open_weight_rows()
    closed_rows = load_closed_weight_rows()
    open_rows = [r for r in open_rows if r["model"] not in ar.EXCLUDE_MODELS]
    print(f"  Open-weight rows : {len(open_rows)}")
    print(f"  Closed-weight rows: {len(closed_rows)}")

    all_rows = add_parse_success(open_rows + closed_rows)

    headline_rows = [r for r in all_rows if r["model"] in HEADLINE_MODELS]
    appendix_rows = [r for r in all_rows if r["model"] in APPENDIX_MODELS]

    print(f"\nDataset views:")
    print(f"  Headline (8 models, no gpt-4o-mini): {len(headline_rows)} rows")
    print(f"  Appendix (9 models, +gpt-4o-mini)  : {len(appendix_rows)} rows")

    headline_report = run_pipeline(
        headline_rows, EXTENSION_DIR / "merged_analysis_report.json",
        "headline (8 models)",
    )
    appendix_report = run_pipeline(
        appendix_rows, EXTENSION_DIR / "appendix_gpt4omini_report.json",
        "appendix (9 models incl. gpt-4o-mini)",
    )

    write_summary_md(headline_report, appendix_report)

    print(f"\n{'=' * 70}")
    print("Merged analysis complete.")


if __name__ == "__main__":
    main()
